# Generated by Django 5.0.3 on 2024-07-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.worker')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.worker'),
        ),
    ]
